name: CyberRadioDriver build

on:
  push:
    branches: [ master, test_workflow ]

jobs:
  build-ubuntu22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: apt-get install -y python3-serial python3-netifaces python3-numpy python3-requests
    - name: Build and Package
      run: ./makedeb cyberradiodriver
    - name: Save Debian Archive
      uses: actions/upload-artifact@v3
      with:
        name: python3-cyberradiodriver
        path: ./*.deb
